server:
  port: 8080

# Spring Boot 的数据源配置
spring:
  datasource:
    name: zzy_crm
    url: jdbc:mysql://localhost:3306/crm_zzy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    suffix: .html

# mybatis-plus???????
mybatis-plus:
  # xml??k??????????????????????? Mapper ??????? XML ???λ???
  mapper-locations: classpath:mapper/*.xml
  # ???????????????,?????????
  global-config:
    db-config:
      #???????? AUTO:"?????ID????" INPUT:"???????ID",ID_WORKER:"???Ψ?ID (????????Ψ?ID)", UUID:"???Ψ?ID UUID";
      id-type: auto
      #??β??? IGNORED:"?????ж?"  NOT_NULL:"?? NULL ?ж?")  NOT_EMPTY:"????ж?"
      field-strategy: NOT_EMPTY
      #?????????
      db-type: MYSQL
  configuration:
    # ??????????????????????:?????????????Java????????????????????
    map-underscore-to-camel-case: true
    # ??????????а?????????У??? MyBatis ?????????????????????
    call-setters-on-nulls: true
    # ??????????е?sql????????????????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  # pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

  # ???????
  #logging:
  #  level:
  #    com.hopu.springbootlogback.dao: debug  #com.hopu.springbootlogback.dao???????????debug
  #  file:   # ????????????・??
  #    path: ./log    #  window??c:/log/   linux :/home/  ???????????????./log
  #config: logback-dev.xml   # ?????xml?????????   ????????logback-spring.xml
logging:
  config: classpath:logback-spring.xml
